# Generated by Django 5.0.6 on 2024-07-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_financial_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
