# Generated by Django 5.0.7 on 2024-08-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_events_course_name_alter_events_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date_of_holding',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
